// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-escrituras.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_escrituras_default = defineTool({
  name: "list_escrituras",
  title: "Listar escrituras",
  description: "Lista los tr\xE1mites de escrituras (compraventa, hipoteca, poder) del usuario autenticado en su organizaci\xF3n activa, ordenados por fecha de actualizaci\xF3n.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("M\xE1ximo de resultados"),
    status: z.string().optional().describe("Filtro opcional por estado")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sb(ctx).from("tramites").select("id, radicado, tipo, status, fecha, updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-cancelaciones.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_cancelaciones_default = defineTool2({
  name: "list_cancelaciones",
  title: "Listar cancelaciones",
  description: "Lista las cancelaciones de hipoteca del usuario autenticado en su organizaci\xF3n activa, ordenadas por fecha de actualizaci\xF3n.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(20).describe("M\xE1ximo de resultados"),
    status: z2.string().optional().describe("Filtro opcional por estado"),
    banco: z2.string().optional().describe("Filtro opcional por nombre del banco acreedor")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, banco }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sb2(ctx).from("cancelaciones").select(
      "id, status, deudor_nombre, deudor_cedula, banco_acreedor, matricula_inmobiliaria, valor_hipoteca, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (banco) q = q.ilike("banco_acreedor", `%${banco}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-cancelacion.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_cancelacion_default = defineTool3({
  name: "get_cancelacion",
  title: "Obtener cancelaci\xF3n",
  description: "Recupera el detalle completo (data_final incluido) de una cancelaci\xF3n de hipoteca por su ID. RLS garantiza que s\xF3lo devuelve cancelaciones de la organizaci\xF3n activa del usuario.",
  inputSchema: {
    id: z3.string().uuid().describe("UUID de la cancelaci\xF3n")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await sb3(ctx).from("cancelaciones").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "No encontrada" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { cancelacion: data }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool4({
  name: "whoami",
  title: "Qui\xE9n soy",
  description: "Devuelve la identidad del usuario autenticado que llama al servidor MCP (ID y email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cmcikwbszokxeepchqib";
var mcp_default = defineMcp({
  name: "sertuss-mcp",
  title: "Sertuss",
  version: "0.1.0",
  instructions: "Herramientas de Sertuss (plataforma notarial colombiana). Permite consultar escrituras y cancelaciones de hipoteca de la organizaci\xF3n activa del usuario autenticado. Usa `whoami` para verificar la conexi\xF3n, `list_escrituras` / `list_cancelaciones` para explorar y `get_cancelacion` para ver el detalle completo de una cancelaci\xF3n por ID.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_escrituras_default, list_cancelaciones_default, get_cancelacion_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
